" be iMproved
set nocompatible

" ---------- Vundle handles plugins ---------- "
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'chip2n/chiptheme'
Bundle 'tpope/vim-surround'
Bundle 'tikhomirov/vim-glsl'
Bundle 'flazz/vim-colorschemes'
Bundle 'vim-scripts/ScrollColors'
Bundle 'tmhedberg/SimpylFold'
Bundle 'xolox/vim-misc'

Bundle 'scrooloose/nerdtree'
let NERDTreeIgnore = ['\.pyc$', '\.hi$', '\.o$', '\.dyn_hi$', '\.dyn_o$']
let NERDTreeQuitOnOpen = 1

Bundle 'scrooloose/syntastic'
let g:syntastic_mode_map = {'mode': 'passive'}

Bundle 'Lokaltog/vim-easymotion'
let g:EasyMotion_leader_key = '<Leader>'

"Bundle 'klen/python-mode'
"let g:pymode_folding = 0
"let g:pymode_options_colorcolumn = 0

Bundle 'xolox/vim-easytags'
let g:easytags_async=1
let g:easytags_syntax_keyword='always'
let g:easytags_on_cursorhold=0
let g:easytags_auto_update=0
let g:easytags_auto_highlight=0

Bundle 'majutsushi/tagbar'

"Bundle 'wincent/command-t'
"if &term =~ "rxvt-unicode" || &term =~ "screen"
"  let g:CommandTCancelMap = ['<ESC>', '<C-c>']
"endif
" NOTE: Install with:
"   > cd ~/.vim/bundle/command-t/ruby/commant-t
"   > ruby extconf.rb
"   > make

Bundle 'ctrlpvim/ctrlp.vim'
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 0
nnoremap <C-b> :CtrlPBuffer <CR>

Bundle 'JazzCore/ctrlp-cmatcher'
" NOTE: Must run .vim/bundle/ctrlp-matcher/install.sh
let g:ctrlp_match_func = {'match': 'matcher#cmatch'}

Bundle 'jlanzarotta/bufexplorer'

"Bundle 'Shougo/unite.vim'

" NOTE: Must be compiled using make
"Bundle 'Shougo/vimproc.vim'

autocmd Filetype java setlocal omnifunc=javacomplete#Complete
autocmd Filetype java map <leader> b :call javacomplete#GoToDefinition()<CR>

:filetype plugin indent on
" -------------------------------------------- "

" Hide buffers instead of closing them
set hidden

" New leader key
let mapleader="ö"
let maplocalleader="ö"

" Disable arrow keys - thou shalt not use them
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" Enables moving between rows of a single line
nnoremap j gj
nnoremap k gk

" Navigate between vim splits
nmap <silent> <C-h> :wincmd h<CR>
nmap <silent> <C-j> :wincmd j<CR>
nmap <silent> <C-k> :wincmd k<CR>
nmap <silent> <C-l> :wincmd l<CR>

" Set split to 80 char width
"nmap <silent> <c-p> :vertical resize 83<CR>

" Set backspace to open/focus NERDTree and Tagbar
nnoremap <BS> :NERDTreeToggle <CR>
nnoremap <S-BS> :TagbarToggle <CR>

" Set space to show ctags of selected tags
nnoremap <Space> <C-]>
nnoremap <S-Space> <C-T>

" Easier 'pagedown' and 'pageup' bindings
"nnoremap <C-j> <C-D>
"nnoremap <C-k> <C-U>

" Enable 256 colors
let &t_Co=256

" Enable syntax highlighting
syntax on
set background=dark
" colorscheme fu
colorscheme test

" Set font for GVim
set guifont=Terminus\ 8

" Set lazy redraw for faster scrolling
set lazyredraw

" Marks too long lines
" NOTE: Theme must highlight OverLength
"augroup vimrc_autocmds
"  autocmd BufEnter * match OverLength /\%81v.\+/
"augroup END

" Mark column 80
"set colorcolumn=80

" Remove annoying interface stuffz
" Menu bar
set guioptions-=m
" Tool bar
set guioptions-=T
" Right scrollbar
set guioptions-=r
" Left scrollbar
set guioptions-=L
" Remove tab bar
set guioptions-=e

" Disables modelines, which prevents some security exploits
set modelines=0

" New horizontal splits appear below current window
set splitbelow
" New vertical splits appear to the right of current window
set splitright

" Set the default encoding to UTF-8
"set encoding=utf-8

" Set the minimum amount of visible lines above/under
" the cursor to 3 (default is 0)
set scrolloff=3

" Set automatic indentation
set autoindent

" Show the modes in the status bar
set showmode

" Show the current command in the status bar
set showcmd

" Enable the wildmenu (shows the tab completion options)
set wildmenu
set wildmode=list:longest

" Highlight the current cursor line
set cursorline

" Set fast terminal connection
set ttyfast

" Show line and character number
set ruler

" Set relativenumber when not in insert mode - numbers otherwise
set relativenumber
set number
"autocmd InsertEnter * :set norelativenumber
"autocmd InsertLeave * :set relativenumber

" Create an undo file to store the undo history
set undofile

" Set tab options
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2

" Set split bar characters
set fillchars+=vert:\

" Allow backspaces to delete text further than insert point
"set backspace=indent,eol,start

" Fold according to syntax - no nesting
"set foldmethod=syntax
"set foldnestmax=1

" Ignore tab-completion for certain files
" Haskell
set wildignore+=*.hi,*.dyn_hi,*.dyn_o
" Images
set wildignore+=*.jpg,*.png
" Misc
set wildignore+=*.o,*.a,*.so,*.swp,*.swo,*.pyc,*.bson

" Per project .vimrc
:set exrc
:set secure

" ----------------------------------------------------------------------
" Save your backups to a less annoying place than the current directory.
" If you have .vim-backup in the current directory, it'll use that.
" Otherwise it saves it to ~/.vim/backup or . if all else fails.
if isdirectory($HOME . '/.vim/backup') == 0
  :silent !mkdir -p ~/.vim/backup >/dev/null 2>&1
endif
set backupdir-=.
set backupdir+=.
set backupdir-=~/
set backupdir^=~/.vim/backup/
set backupdir^=./.vim-backup/
set backup

" Save your swp files to a less annoying place than the current directory.
" If you have .vim-swap in the current directory, it'll use that.
" Otherwise it saves it to ~/.vim/swap, ~/tmp or .
if isdirectory($HOME . '/.vim/swap') == 0
  :silent !mkdir -p ~/.vim/swap >/dev/null 2>&1
endif
set directory=./.vim-swap//
set directory+=~/.vim/swap//
set directory+=~/tmp//
set directory+=.

" viminfo stores the the state of your previous editing session
set viminfo+=n~/.vim/viminfo

if exists("+undofile")
  " undofile - This allows you to use undos after exiting and restarting
  " This, like swap and backups, uses .vim-undo first, then ~/.vim/undo
  " :help undo-persistence
  " This is only present in 7.3+
  if isdirectory($HOME . '/.vim/undo') == 0
    :silent !mkdir -p ~/.vim/undo > /dev/null 2>&1
  endif
  set undodir=./.vim-undo//
  set undodir+=~/.vim/undo//
  set undofile
endif
" ----------------------------------------------------------------------
