" be iMproved
set nocompatible

" ---------- Vundle handles plugins ---------- "
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/syntastic'
Bundle 'Lokaltog/vim-easymotion'
let g:EasyMotion_leader_key = '<Leader>'
Bundle 'tpope/vim-surround'
Bundle 'tikhomirov/vim-glsl'
Bundle 'Twinside/vim-hoogle'
Bundle 'flazz/vim-colorschemes'

:filetype plugin indent on
" -------------------------------------------- "

" Enable 256 colors
let &t_Co=256

" Enable syntax highlighting
syntax on

" COLORS {
        " syntax highlighting groups
        hi Comment      ctermfg=8
        hi Constant     ctermfg=15 
        hi Identifier   ctermfg=4
        hi Statement    ctermfg=2
        hi PreProc      ctermfg=6
        hi Type         ctermfg=4
        hi Special      ctermfg=3
        hi Underlined   ctermfg=7
        hi Ignore       ctermfg=9
        hi Error        ctermfg=11
        hi Todo         ctermfg=1
        hi Normal ctermfg=none ctermbg=none
        hi NonText ctermfg=0 ctermbg=none
        hi Directory        ctermfg=12

        hi VertSplit        ctermfg=black
        hi StatusLine        ctermfg=4 ctermbg=15
        hi StatusLineNC        ctermfg=0

        hi Folded ctermbg=0 ctermfg=8

        hi Pmenu ctermfg=10 ctermbg=0
        hi PmenuSel ctermfg=0 ctermbg=14
        hi LineNr ctermfg=8 ctermbg=0
        hi CursorLine ctermfg=none ctermbg=0 cterm=none
        hi CursorLineNr ctermfg=none ctermbg=0
        hi CursorColumn ctermfg=none ctermbg=0

        hi Visual ctermbg=0
        hi OverLength ctermbg=1 ctermfg=15
        match OverLength /\%81v.\+/

        " Syntax checker colors
        highlight SignColumn ctermbg=none
        hi SyntasticErrorSign ctermfg=1 ctermbg=none
        hi SyntasticWarningSign ctermfg=3 ctermbg=none
        hi SyntasticStyleErrorSign ctermfg=1 ctermbg=none
        hi SyntasticStyleWarningSign ctermfg=3 ctermbg=none
        hi SyntasticErrorLine ctermfg=none ctermbg=none
        hi SyntasticWarningLine ctermfg=none ctermbg=none
        hi SyntasticStyleErrorLine ctermfg=none ctermbg=none
        hi SyntasticStyleWarningLine ctermfg=none ctermbg=none
        hi SpellBad ctermfg=0 ctermbg=3
        hi SpellCap ctermfg=0 ctermbg=1

"}

" Disables modelines, which prevents some security exploits
set modelines=0

" Set the default encoding to UTF-8
"set encoding=utf-8

" Set the minimum amount of visible lines above/under
" the cursor to 3 (default is 0)
set scrolloff=3

" Set automatic indentation
set autoindent

" Show the modes in the status bar
set showmode

" Show the current command in the status bar
set showcmd

" Enable the wildmenu (shows the tab completion options)
set wildmenu
set wildmode=list:longest

" Make the screen flash instead of playing sound when error occurs
set visualbell

" Highlight the current cursor line
set cursorline

" Set fast terminal connection
set ttyfast

" Show line and character number
set ruler

" Always show status line
set laststatus=2

" Set relativenumber when not in insert mode - numbers otherwise
set relativenumber
autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber

" Create an undo file to store the undo history
set undofile

" Enable save on lost focus
au FocusLost * :wa

" Disable arrow keys - thou shalt not use them
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" Enables moving between rows of a single line
nnoremap j gj
nnoremap k gk

" Navigate between vim splits
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-l> :wincmd l<CR>

" Set backspace to open/focus NERDTree
nnoremap <BS> :NERDTreeFocus <CR>

" Set tab options
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

set cindent

" Allow backspaces to delete text further than insert point
set backspace=indent,eol,start

" Hide status line
set laststatus=0

" Fold according to syntax - no nesting
set foldmethod=syntax
set foldnestmax=1
