# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c23093e1-16c6-4465-85d2-25e4078979a8";
      fsType = "ext4";
    };

  fileSystems."/media" =
    { device = "/dev/mapper/luks-949a094d-c9ae-419b-8cd7-b7e5f3d0a2fd";
      fsType = "ext4";
    };

  boot.initrd.luks.reusePassphrases = true;
  boot.initrd.luks.devices = {
    "luks-c23093e1-16c6-4465-85d2-25e4078979a8".device = "/dev/disk/by-uuid/c23093e1-16c6-4465-85d2-25e4078979a8";
    "luks-949a094d-c9ae-419b-8cd7-b7e5f3d0a2fd".device = "/dev/disk/by-uuid/949a094d-c9ae-419b-8cd7-b7e5f3d0a2fd";
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4D28-DE06";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
