#! /bin/sh

#bspc monitor DVI-D-0 -d     
#bspc monitor DVI-I-0 -d  
bspc monitor -d     

desktop_config() {
  bspc config $1 $2
  for M in $(bspc query -M); do
    bspc config -m $M $1 $2
  done
}

desktop_config border_width 1
desktop_config window_gap 12
bspc config top_padding         18
#bspc config border_width        4
#bspc config window_gap          32
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.05

bspc rule -a BSPWM_FRAME --frame
bspc rule -a Gimp floating=on

/home/chip/scripts/panel &
