#! /bin/sh

bspc monitor -d     

bspc config top_padding         18
bspc config border_width        1
bspc config window_gap          12
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

/home/chip/scripts/panel &
