#! /bin/sh

bspc monitor DVI-D-0 -d     
bspc monitor DVI-I-0 -d  
#bspc monitor -d     

bspc config top_padding         14
bspc config border_width        1
bspc config window_gap          8
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.05

bspc rule -a BSPWM_FRAME --frame
bspc rule -a Gimp floating=on

/home/chip/scripts/panel &
