#! /bin/sh
#
# Example panel for LemonBoy's bar

host=$(uname -n)
while read -r line ; do
    case $line in
        S*)
            # clock output
            sys_infos="${line#?}"
            ;;
        T*)
            # xtitle output
            title="${line#?}"
            ;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    O*)
                        # focused occupied desktop
                        wm_infos="$wm_infos %{U#ffffa500+u}%{F#ffffffff}${name}%{-u}"
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos="$wm_infos %{U#ffffa500+u}%{F#ff666060}${name}%{-u}"
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos="$wm_infos %{U#ffffa500+u}%{F#ffffffff}${name}%{-u}"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos="$wm_infos %{F#ffffffff}${name}"
                        ;;
                    f*)
                        # free desktop
                        wm_infos="$wm_infos %{F#ff666060}${name}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos %{Ured+u}%{F#ffffffff}${name}%{-u}"
                        ;;
                    L*)
                        # layout
                        #layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
                        #wm_infos="$wm_infos    \\br\\f6$layout"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "%{l}  %{F#ff5ba7c2} ${host} $wm_infos %{c} %{ffF#666060}$title %{r} $sys_infos  "
done
