#! /bin/sh
#
# Example panel for LemonBoy's bar

. panel_colors

host=$(uname -n)
while read -r line ; do
    case $line in
        S*)
            # clock output
            sys_infos="${line#?}"
            ;;
        T*)
            # xtitle output
            title="${line#?}"
            ;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    O*)
                        # focused occupied desktop
                        wm_infos="$wm_infos %{U$COLOR_FOCUSED_UNDERLINE+u}%{F$COLOR_OCCUPIED_FG}${name}%{-u}"
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos="$wm_infos %{U$COLOR_FOCUSED_UNDERLINE+u}%{F$COLOR_FREE_FG}${name}%{-u}"
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos="$wm_infos %{U$COLOR_FOCUSED_UNDERLINE+u}%{F$COLOR_URGENT_FG}${name}%{-u}"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos="$wm_infos %{F$COLOR_OCCUPIED_FG}${name}"
                        ;;
                    f*)
                        # free desktop
                        wm_infos="$wm_infos %{F$COLOR_FREE_FG}${name}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos %{U$COLOR_URGENT_UNDERLINE+u}%{F$COLOR_URGENT_FG}${name}%{-u}"
                        ;;
                    L*)
                        # layout
                        #layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
                        #wm_infos="$wm_infos    \\br\\f6$layout"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "%{l}  %{F$COLOR_HOST_FG} ${host} $wm_infos %{c} %{F$COLOR_TITLE_FG}$title %{r} $sys_infos  "
done
