#!/bin/bash

VOL=`amixer get Master | awk 'FNR == 5 {print $4}' | tr -d '[]%'`
STATUS=`amixer get Master | awk 'FNR == 5 {print $6}' | tr -d '[]'`

icon=""
if [[ $STATUS == "off" ]]; then
	icon=""
else
	icon=""
fi

bar=""
case $VOL in
	100)
		bar="----------"
		;;
	0)
		bar="%{F#666060}----------"
		;;
	[1-9])
		bar="-%{F#666060}---------"
		;;
	1*)
		bar="--%{F#666060}--------"
		;;
	2*)
		bar="---%{F#666060}-------"
		;;
	3*)
		bar="----%{F#666060}------"
		;;
	4*)
		bar="-----%{F#666060}-----"
		;;
	5*)
		bar="------%{F#666060}----"
		;;
	6*)
		bar="-------%{F#666060}---"
		;;
	7*)
		bar="--------%{F#666060}--"
		;;
	8*)
		bar="---------%{F#666060}-"
		;;
	*)
		bar="----------"
		;;
esac

echo "$icon %{F#bf728f}$bar%{F#ffffff}"
