#!/bin/bash

BAT=`acpi -b | awk '{gsub(/%,/,""); print $4}' | sed 's/%//g'`
STATUS=`acpi -b | awk '{gsub(/,/,""); print $3}'`

icon=""
if [[ $STATUS != "Discharging" ]]; then
	icon=""
elif [[ $BAT -lt 10 ]]; then
	icon=""
elif [[ $BAT -lt 40 ]]; then
	icon=""
elif [[ $BAT -lt 70 ]]; then
	icon=""
else
	icon=""
fi

bar=""
case $BAT in
	100)
		bar="----------"
		;;
	0)
		bar="%{F#77838c}----------"
		;;
	[1-9])
		bar="-%{F#77838c}---------"
		;;
	1*)
		bar="--%{F#77838c}--------"
		;;
	2*)
		bar="---%{F#77838c}-------"
		;;
	3*)
		bar="----%{F#77838c}------"
		;;
	4*)
		bar="-----%{F#77838c}-----"
		;;
	5*)
		bar="------%{F#77838c}----"
		;;
	6*)
		bar="-------%{F#77838c}---"
		;;
	7*)
		bar="--------%{F#77838c}--"
		;;
	8*)
		bar="---------%{F#77838c}-"
		;;
	*)
		bar="----------"
		;;
esac

echo "$icon %{F#bf728f}$bar%{F#ffffff}"
