#! /bin/sh

. panel_colors

LOCATION="/home/chip/scripts/"

flavor=${1:-i3}

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

clock() {
  DATE=$(date "+%T")
  echo "S$DATE"
}

xtitle -sf 'T%s' > "$PANEL_FIFO" &
#clock > "$PANEL_FIFO" &
conky -c "${LOCATION}panel_conky" > $PANEL_FIFO &
#panel_trayer
#stalonetray &

case "$flavor" in
    i3)
        # TODO: must use fork of i3-py to avoid unicode bug
        ${LOCATION}i3_workspaces.py > "$PANEL_FIFO" &
        #${LOCATION}skype.py > "$PANEL_FIFO" &
        cat "$PANEL_FIFO" | ${LOCATION}panel_parser_i3 | lemonbar -f "-*-terminus-medium-*-normal-*-12-*-*-*-c-*-*-1" -f "-*-siji-medium-*-normal-*-10-*-*-*-c-*-*-1" -g 1920x18+0+4 -B "${bar_color_bg}" -F "${bar_color_fg}" -u 2
        ;;
    bspwm)
        bspc config top_padding $PANEL_HEIGHT
        bspc control --subscribe > "$PANEL_FIFO" &
        cat "$PANEL_FIFO" | ${LOCATION}panel_parser_bspwm | lemonbar -f "-*-terminus-medium-*-normal-*-12-*-*-*-c-*-*-1" -f "-*-siji-medium-*-normal-*-10-*-*-*-c-*-*-1" -g 1920x18+0+4 -B "${bar_color_bg}" -F "${bar_color_fg}" -u 2
        ;;
esac

wait
