#!/bin/bash

BAT=`acpi -b | awk '{gsub(/%,/,""); print $4}' | sed 's/%//g'`
STATUS=`acpi -b | awk '{gsub(/,/,""); print $3}'`

icon=""
if [[ $STATUS != "Discharging" ]]; then
	icon=""
elif [[ $BAT -lt 10 ]]; then
	icon=""
elif [[ $BAT -lt 40 ]]; then
	icon=""
elif [[ $BAT -lt 70 ]]; then
	icon=""
else
	icon=""
fi

bar=""
case $BAT in
	100)
		bar="---------"
		;;
	[0-5])
		bar="%{F#666060}---------"
		;;
	[5-9])
		bar="-%{F#666060}--------"
		;;
	[1-2]*)
		bar="--%{F#666060}-------"
		;;
	3*)
		bar="---%{F#666060}------"
		;;
	4*)
		bar="----%{F#666060}-----"
		;;
	5*)
		bar="-----%{F#666060}----"
		;;
	6*)
		bar="------%{F#666060}---"
		;;
	7*)
		bar="-------%{F#666060}--"
		;;
	8*)
		bar="--------%{F#666060}-"
		;;
	*)
		bar="---------"
		;;
esac

echo "$icon %{F#bf728f}$bar%{Fwhite}"
