#! /bin/sh

LOCATION="/home/chip/scripts/"

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor=${1:-bar}

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
#clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &
conky -c "${LOCATION}panel_conky" > $PANEL_FIFO &
panel_trayer

case "$flavor" in
    bar)
        cat "$PANEL_FIFO" | panel_bar | bar-aint-recursive -f "-misc-stlarch-medium-*-normal-*-10-*-*-*-c-*-*-1" -g 1920x18 -B "#171616" -F "#ffffff" -u 2
        ;;
    dzen2)
        . panel_colors
        FONT_FAMILY='DejaVu Sans'
        FONT_SIZE=11
        cat "$PANEL_FIFO" | panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &
        ;;
esac

wait
