#!/bin/bash

BAT=`acpi -b | awk '{gsub(/%,/,""); print $4}' | sed 's/%//g'`
STATUS=`acpi -b | awk '{gsub(/,/,""); print $3}'`

icon=""
if [[ $STATUS != "Discharging" ]]; then
	icon=""
elif [[ $BAT -lt 10 ]]; then
	icon=""
elif [[ $BAT -lt 40 ]]; then
	icon=""
elif [[ $BAT -lt 70 ]]; then
	icon=""
else
	icon=""
fi

bar=""
case $BAT in
	100)
		bar="---------"
		;;
	[0-5])
		bar="%{Fred}---------"
		;;
	[5-9])
		bar="-%{Fred}--------"
		;;
	[1-2]*)
		bar="--%{Fred}-------"
		;;
	3*)
		bar="---%{Fred}------"
		;;
	4*)
		bar="----%{Fred}-----"
		;;
	5*)
		bar="-----%{Fred}----"
		;;
	6*)
		bar="------%{Fred}---"
		;;
	7*)
		bar="-------%{Fred}--"
		;;
	8*)
		bar="--------%{Fred}-"
		;;
	*)
		bar="---------"
		;;
esac

echo "$icon %{Fwhite}$bar%{Fwhite}"
