#!/bin/bash

VOL=`amixer get Master | awk 'FNR == 5 {print $4}' | tr -d '[]%'`
STATUS=`amixer get Master | awk 'FNR == 5 {print $6}' | tr -d '[]'`

icon=""
if [[ $STATUS == "off" ]]; then
	icon=""
else
	icon=""
fi

bar=""
case $VOL in
	100)
		bar="----------"
		;;
	0)
		bar="%{F#77838c}----------"
		;;
	[1-9])
		bar="-%{F#77838c}---------"
		;;
	1*)
		bar="--%{F#77838c}--------"
		;;
	2*)
		bar="---%{F#77838c}-------"
		;;
	3*)
		bar="----%{F#77838c}------"
		;;
	4*)
		bar="-----%{F#77838c}-----"
		;;
	5*)
		bar="------%{F#77838c}----"
		;;
	6*)
		bar="-------%{F#77838c}---"
		;;
	7*)
		bar="--------%{F#77838c}--"
		;;
	8*)
		bar="---------%{F#77838c}-"
		;;
	*)
		bar="----------"
		;;
esac

echo "$icon %{F#bf728f}$bar%{F#ffffff}"
