#!/bin/bash

VOL=`amixer get Master | awk 'FNR == 5 {print $4}' | tr -d '[]%'`
STATUS=`amixer get Master | awk 'FNR == 5 {print $6}' | tr -d '[]'`

icon=""
if [[ $STATUS == "off" ]]; then
	icon=""
else
	icon=""
fi

bar=""
case $VOL in
	100)
		bar="---------"
		;;
	[0-5])
		bar="%{Fred}---------"
		;;
	[5-9])
		bar="-%{Fred}--------"
		;;
	[1-2]*)
		bar="--%{Fred}-------"
		;;
	3*)
		bar="---%{Fred}------"
		;;
	4*)
		bar="----%{Fred}-----"
		;;
	5*)
		bar="-----%{Fred}----"
		;;
	6*)
		bar="------%{Fred}---"
		;;
	7*)
		bar="-------%{Fred}--"
		;;
	8*)
		bar="--------%{Fred}-"
		;;
	*)
		bar="---------"
		;;
esac

echo "$icon %{Fwhite}$bar%{Fwhite}"
